### ISSUE TITLE
Version 6.04 crashes on startup

### ISSUE THREAD

**Issue by JimLuth** [AutomationML/AutomationMLEditor#4]
Version 6.04 crashes on startup with the attached ErrorLog.txt

[ErrorLog.txt](https://github.com/AutomationML/AutomationMLEditor/files/8788911/ErrorLog.txt)

**Comment by JimLuth** [comment]
I had the same failure on multiple computers all with working internet connections.

**Comment by josefprinz** [comment]
The error occurs when the https://github.com/AutomationML/AutomationMLEditor/blob/main/Configuration/Aml.Editor.Configuration.Messages_v2.json file is read. It seems, that the json reader in your version 6.0.4 has a problem, deserializing this file. This is strange, because the version 6.0.3 is able to read the same file. Could you try to start the editor offline (without internet). The model browser will not read any web resources and the browser page should show no content. After reconnecting to the internet (the editor should be kept running) a reload of the model pages is possible by clicking the little globe icon in the status bar.

**Comment by JimLuth** [comment]
The application has the same problem starting without an internet connection.

**Comment by JimLuth** [comment]
You should be able to replicate my problem using [Windows Sandbox](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview). If it matters, my locale is set to US-English.

**Comment by gwkim9444** [comment]
Same Issue

![image](https://user-images.githubusercontent.com/36144078/172959665-2083209e-3ea7-4f7c-8f9c-16dc31ab61f1.png)

**Comment by AutomationML2021** [comment]
I could find the cause for the error. I have switched from newtonsoft.json to system.text.json to deserialize the news and model pages. The DateTime string parsing when the current locale is set to En-Us throws the exception. Jim gave the hint. I will publish a new version soon.

**Comment by JimLuth** [comment]
Could you also provide the installer in English?  My German is not very good.

**Comment by AutomationML2021** [comment]
Version 6.0.5 is published. The release does not contain an installer and is not updated automatically. You can simply unzip the files to your installation folder.
